import { DndContext, useDraggable, useDroppable } from '@dnd-kit/core'
import { Chessboard } from 'react-chessboard'
import { useEffect, useMemo, useReducer, useState } from 'react'
import type { ActionCard, FigureCard, GameState, Move, Square } from './domain'
import { RandomAgent, actionText, beginTurn, endTurn, newGame, playableAction, playableFigures, playMove, seeded, selectFigureCard, useAction } from './engine'
import './app.css'

const random=seeded(Date.now())
type Act={type:'start'}|{type:'begin'}|{type:'select',id:string}|{type:'move',move:Move}|{type:'action',id:string,target?:string}|{type:'end'}
function reducer(s:GameState|undefined,a:Act):GameState|undefined { if(a.type==='start')return newGame(random);if(!s)return s;if(a.type==='begin')return beginTurn(s,random);if(a.type==='select')return selectFigureCard(s,a.id);if(a.type==='move')return playMove(s,a.move,random);if(a.type==='action')return useAction(s,a.id,random,a.target);return endTurn(s) }
const glyph:Record<string,string>={pawn:'P',knight:'N',bishop:'B',rook:'R',queen:'Q',king:'K',joker:'J'}
function Card({card,active,playable,onClick}:{card:FigureCard|ActionCard;active?:boolean;playable?:boolean;onClick?:()=>void}) { const {attributes,listeners,setNodeRef,transform}=useDraggable({id:card.id});return <button ref={setNodeRef} {...attributes} {...listeners} onClick={onClick} className={`card ${card.kind} ${active?'active':''} ${playable?'playable':''}`} style={{transform:transform?`translate(${transform.x}px,${transform.y}px)`:undefined}} title={card.kind==='action'?actionText[card.type][1]:undefined}>{card.kind==='figure'?glyph[card.type]:actionText[card.type][0]}</button> }
function DropZone(){const {setNodeRef,isOver}=useDroppable({id:'discard'});return <div ref={setNodeRef} className={`drop ${isOver?'over':''}`}>Karte ausspielen</div>}
function toFen(board:GameState['board']) {const code:Record<string,string>={pawn:'p',knight:'n',bishop:'b',rook:'r',queen:'q',king:'k'};return [8,7,6,5,4,3,2,1].map(r=>{let out='',empty=0;for(const f of 'abcdefgh'){const p=board[`${f}${r}` as Square];if(!p)empty++;else{if(empty){out+=empty;empty=0}out+=p.color==='white'?code[p.type].toUpperCase():code[p.type]}}return out+(empty||'')}).join('/')}
function App(){const [state,dispatch]=useReducer(reducer,undefined);const [help,setHelp]=useState(false);const [selected,setSelected]=useState<Square>(); const agent=useMemo(()=>new RandomAgent(),[])
 useEffect(()=>{if(!state||state.result||state.current!=='black')return;const t=setTimeout(async()=>{const n=beginTurn(state,random);const d=await agent.chooseTurn(n,random);if('end'in d)dispatch({type:'end'});else{dispatch({type:'begin'});setTimeout(()=>{dispatch({type:'select',id:d.cardId});dispatch({type:'move',move:d.move})},100)}},650);return()=>clearTimeout(t)},[state,agent])
 if(!state)return <main className="start"><h1>Kartenschach</h1><p>Schlage den gegnerischen KÃ¶nig. Figuren bewegen sich nur mit passenden Karten.</p><button onClick={()=>dispatch({type:'start'})}>Neue Partie</button><button className="quiet" onClick={()=>setHelp(true)}>Regelhilfe</button>{help&&<Help close={()=>setHelp(false)}/>}</main>
 const me=state.players.white, active=state.current==='white', selectedCard=me.figures.find(c=>c.id===state.selectedCardId); const onDrop=(from:string,to:string)=>{if(active)dispatch({type:'move',move:{from:from as Square,to:to as Square}});return false}; const act=(c:ActionCard)=>{if(c.type==='reinforce'){const t=window.document.querySelector<HTMLInputElement>('input[data-reinforce]')?.value;dispatch({type:'action',id:c.id,target:t})}else if(c.type==='block'){const t=window.document.querySelector<HTMLInputElement>('input[data-block]')?.value;dispatch({type:'action',id:c.id,target:t})}else dispatch({type:'action',id:c.id})}
 return <DndContext onDragEnd={({active:drag,over})=>{if(over?.id==='discard'){const c=[...me.figures,...me.actions].find(x=>x.id===drag.id);if(c?.kind==='figure')dispatch({type:'select',id:c.id});else if(c)act(c)}}}><main><header><strong>Kartenschach</strong><span>{state.current==='white'?'Du bist am Zug':'KI denkt nach'} Â· {state.phase}</span><button className="quiet" onClick={()=>setHelp(true)}>?</button></header><section className="enemy">Gegnerische Hand: {state.players.black.figures.length+state.players.black.actions.length} verdeckte Karten</section><div className="table"><aside><b>Figurenstapel</b><div className="deck">{state.figures.draw.length}</div><small>Ablage: {state.figures.discard.length}</small></aside><div className="board"><Chessboard id="game" position={toFen(state.board)} onPieceDrop={onDrop} onSquareClick={(s)=>{if(!active||!selectedCard)return;if(selected) {dispatch({type:'move',move:{from:selected,to:s as Square}});setSelected(undefined)}else if(state.board[s as Square]?.color==='white')setSelected(s as Square)}} boardOrientation="white" arePiecesDraggable={active&&!!selectedCard}/><DropZone/></div><aside><b>Actionstapel</b><div className="deck actiondeck">{state.actions.draw.length}</div><small>Ablage: {state.actions.discard.length}</small></aside></div><section className="hand"><h2>Deine Figurenkarten</h2><div>{me.figures.map(c=><Card key={c.id} card={c} active={c.id===state.selectedCardId} playable={playableFigures(state,'white').some(x=>x.id===c.id)} onClick={()=>active&&dispatch({type:'select',id:c.id})}/>)}</div><h2>Deine Action-Karten</h2><div>{me.actions.map(c=><Card key={c.id} card={c} playable={playableAction(state,c)} onClick={()=>active&&act(c)}/>)}</div><div className="targets"><label>VerstÃ¤rkung Feld <input data-reinforce placeholder="z.B. e2" /></label><label>Blockieren Feld <input data-block placeholder="z.B. e7" /></label></div></section>{state.message&&<p className="message">{state.message}</p>}{active&&state.phase==='actions'&&<button className="end" onClick={()=>dispatch({type:'end'})}>Zug ohne Action beenden</button>}{state.result&&<div className="overlay"><h2>{state.result.winner==='white'?'Du gewinnst':'Die KI gewinnt'}</h2><p>Der KÃ¶nig wurde geschlagen.</p><button onClick={()=>dispatch({type:'start'})}>Neue Partie</button></div>}{help&&<Help close={()=>setHelp(false)}/>}</main></DndContext>}
function Help({close}:{close:()=>void}){return <div className="help"><div><button onClick={close}>SchlieÃŸen</button><h2>Kurzregeln</h2><p>Kein Schach, kein Matt: KÃ¶nige dÃ¼rfen bedroht und geschlagen werden. Ziehe zu Beginn eine Figurenkarte, spiele Actions vor dem Zug, und bewege dann eine passende Figur. Joker ersetzen jede Figurenart.</p><p>Bei Verlust einer Figur erhÃ¤lt der Besitzer Action-Karten. Bauer 1, Springer/LÃ¤ufer 2, Turm 3, Dame 5. Doppelzug benÃ¶tigt zwei unterschiedliche Figuren und der erste Zug darf nicht schlagen.</p></div></div>}
export default App
