import { describe, expect, it } from 'vitest'
import { RandomAgent, executeMove, newGame, pseudoMoves, seeded, selectFigureCard, skipFigureMove, useAction } from './engine'
import type { ActionCard, Board, FigureCard, GameState } from './domain'
const p=(type:'pawn'|'knight'|'bishop'|'rook'|'queen'|'king', color:'white'|'black')=>({id:type+color,type,color,moved:false})
const f=(id:string,type:FigureCard['type']):FigureCard=>({id,kind:'figure',type})
describe('rule engine',()=>{
 it('lets knights jump and blocks bishops',()=>{const b:Board={b1:p('knight','white'),c3:p('pawn','white'),d4:p('bishop','white'),e5:p('pawn','white')};expect(pseudoMoves(b,'b1')).toContain('a3');expect(pseudoMoves(b,'d4')).not.toContain('f6')})
 it('allows capturing a king',()=>{const b:Board={a1:p('rook','white'),a8:p('king','black')};expect(executeMove(b,{from:'a1',to:'a8'}).winner).toBe('white')})
 it('promotes pawns',()=>{const b:Board={a7:p('pawn','white')};expect(executeMove(b,{from:'a7',to:'a8',promotion:'queen'}).board.a8?.type).toBe('queen')})
 it('prevents selecting a card before drawing',()=>{const state:GameState={board:{a2:p('pawn','white')},players:{white:{color:'white',figures:[{id:'pawn-card',kind:'figure',type:'pawn'}],actions:[],actionLocked:false},black:{color:'black',figures:[],actions:[],actionLocked:false}},figures:{draw:[],discard:[]},actions:{draw:[],discard:[]},current:'white',phase:'start',turn:1};expect(selectFigureCard(state,'pawn-card')).toBe(state)})
 it('draws an action card when ending without a figure move',()=>{const card:ActionCard={id:'action-card',kind:'action',type:'supply'};const state:GameState={board:{a2:p('pawn','white')},players:{white:{color:'white',figures:[{id:'pawn-card',kind:'figure',type:'pawn'}],actions:[],actionLocked:false},black:{color:'black',figures:[],actions:[],actionLocked:false}},figures:{draw:[],discard:[]},actions:{draw:[card],discard:[]},current:'white',phase:'actions',turn:1};const next=skipFigureMove(state,seeded(1));expect(next.current).toBe('black');expect(next.players.white.actions).toEqual([card]);expect(next.actions.draw).toEqual([])})
 it('does not spawn deactivated action cards in new games',()=>{const inactiveTypes=new Set(['lock','reinforce','block']);const spawnedTypes=newGame(seeded(1)).actions.draw.map(card=>card.type);expect(spawnedTypes).not.toContain('lock');expect(spawnedTypes).not.toContain('reinforce');expect(spawnedTypes).not.toContain('block');expect(spawnedTypes.some(type=>inactiveTypes.has(type))).toBe(false)})
 it('exchanges the selected figure cards',()=>{const action:ActionCard={id:'exchange-action',kind:'action',type:'exchange'};const state:GameState={board:{a2:p('pawn','white')},players:{white:{color:'white',figures:[f('keep','king'),f('swap-a','pawn'),f('swap-b','bishop')],actions:[action],actionLocked:false},black:{color:'black',figures:[],actions:[],actionLocked:false}},figures:{draw:[f('new-a','rook'),f('new-b','queen')],discard:[]},actions:{draw:[],discard:[]},current:'white',phase:'actions',turn:1};const next=useAction(state,action.id,seeded(1),'swap-a,swap-b');expect(next.players.white.figures.map(card=>card.id)).toEqual(['keep','new-b','new-a']);expect(next.figures.discard.map(card=>card.id)).toEqual(['swap-a','swap-b']);expect(next.players.white.actions).toEqual([])})
 it('trades the offered opponent card for the selected own card',()=>{const action:ActionCard={id:'trade-action',kind:'action',type:'trade'};const state:GameState={board:{a2:p('pawn','white')},players:{white:{color:'white',figures:[f('give','pawn'),f('keep','king')],actions:[action],actionLocked:false},black:{color:'black',figures:[f('offer','queen'),f('foe-keep','rook')],actions:[],actionLocked:false}},figures:{draw:[],discard:[]},actions:{draw:[],discard:[]},current:'white',phase:'actions',turn:1};const next=useAction(state,action.id,seeded(1),'offer:give');expect(next.players.white.figures.map(card=>card.id)).toEqual(['keep','offer']);expect(next.players.black.figures.map(card=>card.id)).toEqual(['foe-keep','give']);expect(next.players.white.actions).toEqual([])})
 it('prioritizes captures for the computer',async()=>{const state:GameState={board:{a8:p('rook','black'),b8:p('knight','black'),a1:p('pawn','white')},players:{white:{color:'white',figures:[],actions:[],actionLocked:false},black:{color:'black',figures:[{id:'rook-card',kind:'figure',type:'rook'},{id:'knight-card',kind:'figure',type:'knight'}],actions:[],actionLocked:false}},figures:{draw:[],discard:[]},actions:{draw:[],discard:[]},current:'black',phase:'actions',turn:1};await expect(new RandomAgent().chooseTurn(state,seeded(1))).resolves.toEqual({cardId:'rook-card',move:{from:'a8',to:'a1'}})})
})
